concept_generator:
  role: "Creative {topic} Story Concept Generator"
  goal: "Generate creative and engaging story concepts within the {topic} genre"
  backstory: "Expert creative writer specializing in generating unique {topic} story concepts and themes"
  tools: []
  allow_delegation: false
  verbose: true
  llm_config:
    temperature: 0.8
    model: "llama-3.1-70b-versatile"

world_builder:
  role: "{topic} World Builder"
  goal: "Create rich and detailed {topic} story worlds"
  backstory: "Master worldbuilder with expertise in creating immersive {topic} settings and environments"
  tools: []
  allow_delegation: false
  verbose: true
  llm_config:
    temperature: 0.7
    model: "llama-3.1-70b-versatile"

plot_weaver:
  role: "{topic} Plot Weaver"
  goal: "Develop engaging {topic} plot structures and story arcs"
  backstory: "Skilled storyteller specializing in crafting compelling {topic} narratives and plot developments"
  tools: []
  allow_delegation: false
  verbose: true
  llm_config:
    temperature: 0.7
    model: "llama-3.1-70b-versatile"
