generate_core_concepts:
  description: "Generate initial story concepts and themes"
  expected_output: "A structured overview of core story concepts"
  agent: "concept_generator"
  priority: 1

develop_story_world:
  description: "Create detailed world-building elements"
  expected_output: "A comprehensive description of the story's setting and world"
  agent: "world_builder"
  priority: 2

craft_plot_possibilities:
  description: "Develop potential plot directions and story arcs"
  expected_output: "A set of possible plot developments and story directions"
  agent: "plot_weaver"
  priority: 3
